### ISSUE TITLE
Compilable opton

### ISSUE THREAD

**Issue by finanalyst** [briandfoy/raku-PrettyDump#11]
If a structure made humanly readable with this module is saved to disk, it cannot be compiled with, eg. `my $structure = EVALFILE 'PrettyDumpedData`

This can be overcome - I think - by calling four handles Array,LIst,Match,Hash so that `:start` and `:end` match Raku syntax. 

It would be nice if this was available in the Module as an option, eg. `:compilable`

**Comment by briandfoy** [comment]
I'm not so sure about this one because there are lots of issues with serializing data and bringing it back. Consider the problems Perl 5 had with Data::Dumper and Storable.

I'm not against this idea so far, so if someone came up with a patch that isn't that disruptive it's certainly something I'd consider.

**Comment by finanalyst** [comment]
I found a simple way to use your module, but it took a lot to work out. I only want simple structures, not closures.

Perhaps including this in the documentation would be good, and provide caveats about serialisation of things like closures.

For example, I changed the Array handler to:
```
    my $array-code = -> PrettyDump $pretty, $ds, Int:D :$depth = 0 --> Str {
        $pretty.Array($ds, :start<[>)
    };
    $pretty.add-handler: 'Array', $array-code;
```
This then produced and Array that recompiles.

**Comment by briandfoy** [comment]
Well, the first paragraph of the documentation is (and has been)

> This module creates nicely formatted representations of your data
structure for your viewing pleasure. It does not create valid Raku
code and is not a serialization tool.
